DEBUG:asyncio:Using proactor: IocpProactor
INFO:uvicorn.error:Started server process [29480]
INFO:uvicorn.error:Waiting for application startup.
INFO:pythonConfig:GPU available: True
INFO:pythonConfig:<torch.cuda.device object at 0x00000194656ED790>
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Uvicorn running on http://localhost:8005 (Press CTRL+C to quit)
INFO:pythonConfig:The model is: ../models/HRNet.pkl
WARNING:pythonConfig:Unexpected err=FileNotFoundError(2, 'No such file or directory'), type(err)=<class 'FileNotFoundError'>
INFO:pythonConfig:Images will imported from: C:\Users\hatho\OneDrive\CASA\BEAM_RAW_Files-main\test-image
INFO:pythonConfig:Input Images are:
C:\Users\hatho\OneDrive\CASA\BEAM_RAW_Files-main\test-image\2020_RGB_10cm_BZ_064.tif
INFO:pythonConfig:The model is: undefined
WARNING:pythonConfig:Unexpected err=FileNotFoundError(2, 'No such file or directory'), type(err)=<class 'FileNotFoundError'>
